config/routes.rb
Rails.application.routes.draw do
  resources :shops
  resources :shelves
  resources :shelf_stats
  resources :shelf_daily_stats
  resources :regions
  resources :product_groups
  resources :notifications
  resources :countries
  resources :commercial_networks
  resources :cities
  resources :products
  resources :companies
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id              :bigint           not null, primary key
#  deleted_at      :datetime
#  message         :text
#  notifiable_type :string
#  read_at         :datetime
#  status          :integer          not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  notifiable_id   :bigint
#
# Indexes
#
#  index_notifications_on_created_at                         (created_at)
#  index_notifications_on_deleted_at                         (deleted_at)
#  index_notifications_on_notifiable_id_and_notifiable_type  (notifiable_id,notifiable_type)
#  index_notifications_on_read_at                            (read_at)
#  index_notifications_on_updated_at                         (updated_at)
#
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: %i[ show edit update destroy ]

  # GET /notifications or /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1 or /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications or /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: "Notification was successfully created." }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1 or /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: "Notification was successfully updated." }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1 or /notifications/1.json
  def destroy
    @notification.destroy!

    respond_to do |format|
      format.html { redirect_to notifications_path, status: :see_other, notice: "Notification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notification_params
      params.require(:notification).permit(:status, :message, :notifiable_id, :notifiable_type)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= simple_form_for(@notification) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :status %>
    <%= f.input :message %>
    <%= f.input :notifiable_id %>
    <%= f.input :notifiable_type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/notifications/_notification.html.erb
<div id="<%= dom_id notification %>">
  <p>
    <strong>Status:</strong>
    <%= notification.status %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= notification.message %>
  </p>

  <p>
    <strong>Notifiable:</strong>
    <%= notification.notifiable_id %>
  </p>

  <p>
    <strong>Notifiable type:</strong>
    <%= notification.notifiable_type %>
  </p>

</div>

app/views/notifications/edit.html.erb
<% content_for :title, "Editing notification" %>

<h1>Editing notification</h1>

<%= render "form", notification: @notification %>

<br>

<div>
  <%= link_to "Show this notification", @notification %> |
  <%= link_to "Back to notifications", notifications_path %>
</div>

app/views/notifications/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Notifications" %>

<h1>Notifications</h1>

<div id="notifications">
  <% @notifications.each do |notification| %>
    <%= render notification %>
    <p>
      <%= link_to "Show this notification", notification %>
    </p>
  <% end %>
</div>

<%= link_to "New notification", new_notification_path %>

app/views/notifications/new.html.erb
<% content_for :title, "New notification" %>

<h1>New notification</h1>

<%= render "form", notification: @notification %>

<br>

<div>
  <%= link_to "Back to notifications", notifications_path %>
</div>

app/views/notifications/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @notification %>

<div>
  <%= link_to "Edit this notification", edit_notification_path(@notification) %> |
  <%= link_to "Back to notifications", notifications_path %>

  <%= button_to "Destroy this notification", @notification, method: :delete %>
</div>